### ISSUE TITLE
Use Customer-Style for Barcodescanner

### ISSUE THREAD

**Issue by MoSeMue** [julienboulay/ngx-barcode-scanner#52]
Hi,
How is it possible to adapt the barcode scanner with your own css (height / width). I've already tried something but unfortunately without success

**Comment by julienboulay** [comment]
Hi @MoSeMue,

From version v0.1.1 you can now set the following properties on the components

**barcode-scanner-livestream** : `maxWidth` and `maxHeight`
**barcode-scanner-livestream-overlay** : `width`, `height`, `maxWidth` and `maxHeight`

Let me know if it fits your needs.

**Comment by joepb** [comment]
I've been trying to scale the scanner to fit the box, but haven't been able to do it.
```css
barcode-scanner-livestream {
    .scanner {
        position: absolute;
        top: 0;
        bottom: 0;
        left: 0;
        right: 0;
        video {
            object-fit: cover;
        }
    }
}
```
This would work, if it would actually function. If I set this in chrome on the `.scanner` and `video` object, it does exactly what I would want. But in how Angular handles (s)css, this doesn't really propagate in a live setup.
(It doesn't really scale the overlay well, but I'm not using that in a live setup anyhow.)

Would be great to be able to somehow do this scale-to-cover mode.
